# Generated by Django 3.1.1 on 2020-11-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_information',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basic_information',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
