# Generated by Django 3.1.1 on 2020-11-11 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyProfile', '0002_auto_20201111_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=200, null=True)),
                ('projectTools', models.CharField(max_length=200, null=True)),
                ('projectDescription', models.TextField(null=True)),
                ('projectImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
