# Generated by Django 3.1.1 on 2020-11-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectImage',
            field=models.ImageField(blank=True, null=True, upload_to='Project Image'),
        ),
    ]
