# Generated by Django 3.1.1 on 2020-11-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0004_auto_20201111_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectDemo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projectGithub',
            field=models.URLField(blank=True, null=True),
        ),
    ]
