# Generated by Django 3.1.1 on 2020-11-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='subject',
        ),
    ]
