# Generated by Django 3.1.1 on 2020-11-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0007_auto_20201112_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
