# Generated by Django 3.1.1 on 2020-11-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0008_programming'),
    ]

    operations = [
        migrations.AddField(
            model_name='programming',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
