# Generated by Django 3.1.1 on 2020-11-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0009_programming_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programming',
            old_name='logo',
            new_name='picture',
        ),
    ]
